#!/usr/bin/env node

// Test fixture. Must be run with cwd set to a directory containing
// visual-review-tasks.json — the ShellAgentAdapter spawns commands with
// cwd = ReviewContext.outputDir, which is how this fixture finds it.

import { readFileSync } from "node:fs";

const manifest = JSON.parse(readFileSync("visual-review-tasks.json", "utf8"));
const task = manifest.tasks[0];

console.log(
  JSON.stringify({
    source_pdf: manifest.source_pdf,
    corrections: task
      ? [
          {
            page: task.page,
            region_id: task.region_id,
            crop: task.crop,
            kind: task.kind,
            corrected_extraction: {
              fake_agent: true,
              summary: `Reviewed ${task.crop}`,
            },
            notes: "Generated by fake Codex fixture.",
          },
        ]
      : [],
  }),
);
